feat: added pan flows component as a json text
takenet/blip-cards-vue-components pull request #252
Opened 2024-08-22 14:48 UTC by WillianLomeu

2024-08-22 15:16 UTC, VMarchena approved these changes

2024-08-22 16:49 UTC, Plezito approved these changes

2024-08-27 18:47 UTC, Plezito commented on src/components/BlipGroupCard.vue
> -          if (currentMessageMemberInfo) {
Please review this merge and keep this if as was before

2024-08-27 18:59 UTC, Plezito commented on package-lock.json
This lockfileVersion is now 3. Did you use node version 14 to install the dependencies?

2024-08-30 18:33 UTC, Plezito requested changes

2024-08-30 18:33 UTC, Plezito commented on src/components/ApplicationJSon.vue
> +      v-if="document.type === 'interactive' && document.interactive.type === 'cta_url'"
This should be a v-else-if now that your <json-text> is on top of it

2024-08-30 19:37 UTC, Plezito approved these changes

2024-08-30 20:03 UTC, mpamaro approved these changes

2024-08-30 20:03 UTC, merged

2024-09-02 12:59 UTC, samuelsilvaop commented
:tada: This PR is included in version 3.34.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/blip-cards/v/3.34.0)
- [GitHub release](https://github.com/takenet/blip-cards-vue-components/releases/tag/v3.34.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: